### ISSUE TITLE
.pdf won't display

### ISSUE THREAD

**Issue by bisraelsen** [rschroll/litex#18]
First of all thanks for this plugin. I am excited it exists.

I have followed the docs to the best of my ability but cannot get the .pdf to display when using the local .litexrc

Here is an example of my code (which is just a bit different than the one in the documentation):
```json
{ "file": { "commands": ["pdflatex -interaction=nonstopmode %f"] },
  "project": { "filename": "myFile.tex",
               "commands": ["pdflatex -interaction=nonstopmode --synctex=1 %f",
                            "biber %b",
                            "pdflatex -interaction=nonstopmode --synctex=1 %f"]}}
```

This will successfully build the file. I get some document around 25 pages and can view it with another editor, however I don't see any output in the internal .pdf viewer.

I see have also tried adding something like:

` "PDF-viewer": "internal" `

to no avail. Although I'm not sure if I added that correctly when I did it, and I don't think it should be necessary.

Am I doing something incorrectly?

Thanks!!

**Comment by rschroll** [comment]
Some basic questions first:


- Are you having problems only with that specific litexrc file, or does 
it always fail?
- What operating system are you using?
- Have you installed Poppler?
- Can you run pdftoppm from the command line?

You shouldn't need to set the "PDF-viewer" key, unless you want to use 
an external viewer.

**Comment by bisraelsen** [comment]
- This is with all litexrc files. It has not worked yet
- Xubuntu 14.04
- I have installed Poppler-utils from the repository
- I have never used pdftoppm before, but when I run it in the command line with a .pdf as an argument it starts printing a bunch of stuff to the terminal

As an aside if I did want to make an external viewer start would this be the right synatx? I would like to get that going at least.

```json
{ "file": { "commands": ["pdflatex -interaction=nonstopmode %f"] },
  "project": { "filename": "myFile.tex",
               "commands": ["pdflatex -interaction=nonstopmode --synctex=1 %f",
                            "biber %b",
                            "pdflatex -interaction=nonstopmode --synctex=1 %f"]},
   "PDF-viewer":["my command here"]}
```

Hopefully this helps. Let me know if you need something else.

**Comment by rschroll** [comment]
That's very odd.  I develop on Ubuntu, so I'd expect it to work on all 
the variants.  Can you check LightTable's console to see if there are 
any messages or errors there?


To specify an external viewer, use "PDF-viewer": "external-command %o".

**Comment by bisraelsen** [comment]
There is nothing in the console, only in the logs section o fthe external PDF-viewer window that pops up. Still, the internal pdf-viewer doesn't show anything. The logs say a .pdf file was produced successfully, and I can verify that by opening the .pdf manually.

If I try using an external viewer the logs go to the LightTable console (as they should) and still give the same output as the previous case. However, the external viewer does not open either.... I know the command works because I have tried it in the terminal.

I don't feel like I am being very helpful, is there somewhere I can look to see more details about what is going on?

Thanks!

**Comment by rschroll** [comment]
Litex will only output the logs to the console if it detects an error, 
and in this case it won't try to open a viewer.  I think what's 
happening is that Litex thinks your compilation command is exiting with 
error status, and therefore it isn't triggering the viewer.  What's odd 
is that the PDF file is being produced, which suggests that nothing's 
wrong.


Can you check through the compilation output and see if you find 
something that looks like an error?  If you post it to the bug, I'll 
take a look at it too.

**Comment by bisraelsen** [comment]
There are some errors during compilation, but as far as I know they are not correctable (one, I've learned from forums is basically a warning message).

You should know it is pulling up the viewer window but nothing is displayed (you probably know that but I wanted to make it clear).

I'll get the errors for you.

**Comment by rschroll** [comment]
If you can post the output of the compilation commands, that would be 
helpful.


Litex shouldn't be tripped up by warnings.  It only looks at the exit 
code of the command it executes.  If this indicates an error, it stops 
processing and won't load the PDF.  (After all, it's likely incomplete, 
and you'd probably rather see the previous complete version until you 
fix things.)  I'd be surprised if we were getting a non-zero exit code 
for a non-fatal error, but stranger things have happened.

**Comment by bisraelsen** [comment]
The log file is pretty huge. Here is a link:

[log](https://drive.google.com/file/d/0B0iXrcAVL6lZeGoyOURyWnV4OEE/view?usp=sharing)

Hopefully this helps.

**Comment by rschroll** [comment]
This compilation has produced several errors.  The first is,

> ! LaTeX Error: Command \bibhang already defined.
>                Or name \end... illegal, see p.192 of the manual.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...
> 
> l.427 \newlength{\bibhang}
> 
> Your command was ignored.
> Type  I <command> <return>  to replace it with another command,
> or  <return>  to continue without it.
Because of these errors, latex returns a non-zero exit code, which 
Litex (correctly) takes as a sign to stop processing.

It looks like all the errors are just attempts to redefine macros.  The 
problem may be as simple as a package being included twice.  Ignoring 
them may be fine for now, but I'd recommend against that.  Eventually, 
you'll make another error that won't be benign, and it'll be a lot 
easier to see what it is when you don't have to distinguish that one 
from all of this other output.

Incidentally, this is why I recommend running latex with the 
-halt-on-error flag.  It ensures the error will always show up at the 
end of the logs.  It also keeps benign errors from sneaking in when 
you're not paying attention.

Pontification aside, you can make Litex ignore these problems by 
ensuring that the command you run always returns an exit code of zero. 
One way of doing this would be to use a command like
	["pdflatex -interaction=nonstopmode %f || true"]
Do note that this will cause all errors to be ignored by Litex, so the 
logs will not be displayed.

Litex is doing the right thing, IMO, and since there is a workaround I 
don't feel there's a need to add an option.  I'll edit the README to 
better specify this behavior, though.
