### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by chaffra** [rschroll/litex#21]
I cloned the latest litex into the plugin directory. I opened a tex file. I do Ctrl+Enter but nothing happens, not even some feedback in the console. Also I cannot search for litex commands as if it is not installed, but the files are in the plugin folder and the plugin manager says it's installed.

**Comment by chaffra** [comment]
Never mind. I had to restart the editor. :-)

**Comment by rschroll** [comment]
Glad you could work it out.  It's a mystery to me when Light Table 
needs to be restarted and when it picks things up automatically.
